### ISSUE TITLE
Wiki misleading instructions

### ISSUE THREAD

**Issue by fmenemo** [UNIZAR-30246-WebEngineering/lab2-big-ws#2]
When describing the procedure to push the changes after having modified a small piece of tests, somehow a new branch, which hasn't been refered to in the entire document appears: 'control' branch. What is this branch? Should we also have a third branch apart from test and master? Is it master? Would appreciate some clarification.

>In your master branch update your corresponding row in README.md with the link to your **CONTROL** branch, the Travis badge for your **CONTROL** branch and an ultrashort description of what was explored.

Also, I haven't clearly understood what do I have to do in order to get the bonus. Is it simply creating a spring controller for `/ws` using the example implementation of `translatorendpoint.java` with some sort of GUI? Would also appreciate some clarification on this.

Thanks

**Comment by fjlopez** [comment]
Replaced CONTROL by TEST

**Comment by fjlopez** [comment]
Fixed bonus explanation.
